mongo:
  image: mongo:3.2.11
  volumes:
    - /data/db/mongo
  ports:
      - "27017:27017"

redis:
    image: redis
    volumes:
      - /data/db/redis
    ports:
      - "6379:6379"

postgres:
  restart: always
  image: postgres
  volumes:
    - /data/db/postgres
  ports:
    - "5432"
